name: Check Branch Name

on:
  pull_request:
    types: [opened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check branch name
        run: |
          #!/bin/bash

          # Определяем паттерн для имени ветки
          PATTERN='^feature/[0-9]+$'

          # Получаем имя ветки из переменной окружения
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            pr_number=$(echo "$GITHUB_REF" | sed 's|refs/pull/||;s|/merge||')
            branch_name=$(curl -s \
              -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$pr_number" | \
              jq -r '.head.ref')
          else
            branch_name=$(echo "$GITHUB_REF" | sed 's|refs/heads/||')
          fi

          # Проверяем соответствие имени ветки паттерну
          if [[ "$branch_name" =~ $PATTERN ]]; then
            echo "Branch name '$branch_name' is valid."
          else
            echo "Branch name '$branch_name' does not match pattern '$PATTERN'."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
