name: Check Branch Name

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run branch name check
        run: python ../scripts/check_branch_name.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
