name: Commit Message Lint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5
        with:
          config: commitlint-config-conventional
