name: Check branch name

on:
  push:
    branches: # all branches except main develop c2c-develop
      - '**' 
      - '!main' 
      - '!develop'
      - '!c2c-develop'

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка имени ветки
        run: |
          if [[ "${GITHUB_REF##*/}" != feature/* ]]; then
            echo "Недопустимое имя ветки: ${GITHUB_REF##*/}"
            exit 1
          fi
