name: Check branch name

on:
  push:
    branches:
      - '**'  # срабатывает на любые ветки

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка имени ветки
        run: |
          if [[ "${GITHUB_REF##*/}" != feature/* or "${GITHUB_REF##*/}" != main ]]; then
            echo "Недопустимое имя ветки: ${GITHUB_REF##*/}"
            exit 1
          fi
